version: '3.4'
 
networks:
    myAppNetwork:
    
services:
    SqlServerDb:
            container_name: SqlServerContainer
            image: mcr.microsoft.com/mssql/server:2017-latest
            ports:
                - 8002:1433
            environment:
                - ACCEPT_EULA=Y
                - MSSQL_SA_PASSWORD=myStong_Password123#
    WebApi:
            container_name: CvApiContainer
            image: ${DOCKER_REGISTRY-}cv
            ports:
                - 8001:8080 
            build:
              context: .
              dockerfile: Cv/Dockerfile
            depends_on:
                - SqlServerDb